name: Translate Portuguese to Tupi

on:
  push:
    branches:
      - home

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # J치 est치 atualizado para v3

    - name: Set up Python
      uses: actions/setup-python@v4  # J치 est치 atualizado para v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run translation script
      run: python translation.py

    - name: Commit translated file
      run: |
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git add Tupi_citations_(1).xlsx
        git commit -m "Add translated file"
        git push origin home
